env:
  RUBY_VERSION: 2.5.3

name: Rails tests
on: [push,pull_request]
jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1.31.1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install sqlite 3 
        run: sudo apt-get install libsqlite3-dev
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.1
        with:
          node-version: '8.x'
      - run: npm install -g yarn
      - name: yarn install, build, and test
        run: yarn
      - name: Install dependencies
        run: |
          gem install bundler -v '1.16.6'
          bundler install
      - name: Create database
        run: |
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test
      - name: Run tests
        run: bundler exec rake
